### ISSUE TITLE
Crash when raising error

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#421]
```ruby
(dao) load net
= none
(dao) s = net.bind(343)
= TCPListener[0245E7E8]
(dao) for (x in s) 1 # error, missing listen() call

Program received signal SIGSEGV, Segmentation fault.
0x6b564066 in DaoException_Init (self=0x244d2f8, proc=0x595a68,
    summary=0x6f948340 <neterr+720> "Socket not in the listening state",
    dat=0x0) at kernel/daoStdtype.c:4080
4080            if( vmc && rout->body->vmCodes->size ) line = annotCodes[id]->li
ne;
(gdb) bt
#0  0x6b564066 in DaoException_Init (self=0x244d2f8, proc=0x595a68,
    summary=0x6f948340 <neterr+720> "Socket not in the listening state",
    dat=0x0) at kernel/daoStdtype.c:4080
#1  0x6b544900 in DaoProcess_RaiseExceptionEx (self=0x595a68,
    etype=0x244d190,
    info=0x6f948340 <neterr+720> "Socket not in the listening state")
    at kernel/daoProcess.c:6022
#2  0x6b5449da in DaoProcess_RaiseException (self=0x595a68,
    type=0x24658e4 "Error::Network",
    info=0x6f948340 <neterr+720> "Socket not in the listening state",
    data=0x0) at kernel/daoProcess.c:6041
#3  0x6b544c13 in DaoProcess_RaiseEx (self=0x595a68,
    type=0x6f948070 <neterr> "Network",
    info=0x6f948340 <neterr+720> "Socket not in the listening state", err=1)
    at kernel/daoProcess.c:6073
#4  0x6b544c70 in DaoProcess_RaiseError (self=0x595a68,
    type=0x6f948070 <neterr> "Network",
    info=0x6f948340 <neterr+720> "Socket not in the listening state")
```

**Comment by daokoder** [comment]
Fixed.
