### ISSUE TITLE
load-import crashes

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#459]
```ruby
(dao) load net import net

Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
#1  0x00007ffff78c9611 in DString_AppendBytes (self=0x606590, chs=0x0, n=2569)
    at kernel/daoString.c:430
#2  0x00007ffff78c96e3 in DString_Append (self=0x606590, chs=0x6fdd00)
    at kernel/daoString.c:440
#3  0x00007ffff7938af9 in DaoParser_MakeCodes (self=0x6077d0, start=0, end=5, 
    output=0x606590) at kernel/daoParser.c:2471
#4  0x00007ffff79391fb in DaoParser_Preprocess (self=0x6077d0)
    at kernel/daoParser.c:2578
#5  0x00007ffff7937ad7 in DaoParser_ParseScript (self=0x6077d0)
    at kernel/daoParser.c:2196
#6  0x00007ffff78eb7e4 in DaoProcess_Eval (self=0x606ad0, ns=0x606000, 
    source=0x63a954 "load net import net") at kernel/daoProcess.c:739
#7  0x00007ffff7989e56 in DaoVmSpace_Interun (self=0x604c30, callback=0x0)
    at kernel/daoVmspace.c:1337
#8  0x00007ffff798b6e1 in DaoVmSpace_RunMain (self=0x604c30, 
    file=0x7ffff7bb5684 <dao_string+4> "") at kernel/daoVmspace.c:1735
#9  0x0000000000401496 in main (argc=1, argv=0x7fffffffde18)
    at kernel/daoMain.c:294
```

**Comment by daokoder** [comment]
Fixed.
